### ISSUE TITLE
Warning messages in RunPCA()

### ISSUE THREAD

**Issue by marypiper** [hbctraining/scRNA-seq#1]
#1. Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.

#2. In PrepDR(object = object, features = features, verbose = verbose) :
  The following 15 features requested have not been scaled (running reduction without them): RAD51, CDC45, E2F8, DTL, EXO1, UHRF1, ANLN, GTSE1, NEK2, HJURP, DLGAP5, PIMREG, KIF2C, CDC25C, CKAP2L

Include as note, with how to run with svd instead

**Comment by rkhetani** [comment]
I don't know what it means to "how to run with svd instead"

**Comment by marypiper** [comment]
this is no longer a warning that is output - closing issue
