### ISSUE TITLE
how many cells do we expect?

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq#10]
QC set-up: add unknown # of cells expected - look into paper and see if we can find this number

**Comment by rkhetani** [comment]
@jihe-liu Can you look into this, and we can touch base on Thursday 11/21?

**Comment by jihe-liu** [comment]
From the paper, 12,138 and 12,167 cells were identified (after removing doublets) for control and stimulated pooled samples, respectively.

**Comment by marypiper** [comment]
I added this to the QC, but maybe should add to set-up section too

**Comment by marypiper** [comment]
I added to the metadata section as well for @rkhetani
