### ISSUE TITLE
If pooled, separate the cells into the 8 samples 

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq#12]
Find out from the paper if they have a list of barcodes to identify which cell came from which sample (of the 8)

**Comment by mistrm82** [comment]
update Intro markdown to include this information as in : https://github.com/hbctraining/scRNA-seq/issues/11

**Comment by jihe-liu** [comment]
The paper did not sequence individual samples #11 . The pooled sample could be demultiplexed to individual samples by their tool, demuxlet, though. The demultiplexed individuals were later used for DESeq2 DGE analysis in the paper.

**Comment by marypiper** [comment]
Using dataset combined as described here for DE: http://biocworkshops2019.bioconductor.org.s3-website-us-east-1.amazonaws.com/page/muscWorkshop__vignette/
