### ISSUE TITLE
update images in marker identification

### ISSUE THREAD

**Issue by rkhetani** [hbctraining/scRNA-seq#26]
https://github.com/hbctraining/scRNA-seq/blob/master/lessons/09_merged_SC_marker_identification.md

**Comment by rkhetani** [comment]
Images obtained in class were not the same as the ones in the lesson.

**Comment by rkhetani** [comment]
Update tables too.

**Comment by mistrm82** [comment]
The problem here is due to the normalizing. Assigning the default assay to "RNA" does not undo the  normalization that happens in clustering QC.

```
# Select the RNA counts slot to be the default assay
DefaultAssay(seurat_integrated) <- "RNA"

# Normalize RNA data for visualization purposes
seurat_integrated <- NormalizeData(seurat_integrated, verbose = FALSE)
```

Material figures and tables were generated using the "RNA" slot (counts), in class it was normalized data

**Comment by mistrm82** [comment]
Solution:

Run the FindMarkers with the counts. Run the visualization with the counts(?)

https://github.com/satijalab/seurat/wiki/Assay

**Comment by marypiper** [comment]
I updated the images, but I haven't updated tables - I am unsure why they would need to be updated. Asking Jihe to run through and see whether the tables need to be updated. 

Also, we can specify whether to use raw counts or normalized with the following code: 
```

RNA_raw_assay <- seurat_integrated@assays$RNA@counts

seurat_integrated[['RNA_raw']] <- CreateAssayObject(counts = RNA_raw_assay)

RNA_norm_assay <- seurat_integrated@assays$RNA@data

seurat_integrated[['RNA_norm']] <- CreateAssayObject(counts = RNA_norm_assay)

DefaultAssay(seurat_integrated) <- "RNA_norm"
```
