### ISSUE TITLE
Update packages needed for installation

### ISSUE THREAD

**Issue by jihe-liu** [hbctraining/scRNA-seq#27]
Some packages are no longer needed for the current analysis workflow: Matrix.utils, devtools, AnnotationHub, ensembldb. They could be removed from pre-work installation instruction. Note that AnnotationHub and ensembldb are still needed if people want to generate annotation file themselves.

**Comment by rkhetani** [comment]
Updated packages by removing matrix.utils and added a note about multtest in case of issue with Seurat installation.

If we end up needing matrix.utils, we can follow instructions to install it with devtools from here - https://github.com/cole-trapnell-lab/monocle3/issues/288

**Comment by marypiper** [comment]
Jihe will go back and verify installations are appropriate then close issue if good.

**Comment by jihe-liu** [comment]
Removed Matrix.utils and devtools. Retained annotationhub and ensembldb because they are needed to run code in linked lesson.
