### ISSUE TITLE
use readMM() to convert standard matrix into a sparse matrix

### ISSUE THREAD

**Issue by vasighi** [hbctraining/scRNA-seq#30]
for creating count data object, you use readMM() function from the Matrix package to turn our standard matrix into a sparse matrix. However, the data I downloaded is not standard. from where I can download the standard data with zeros?

**Comment by marypiper** [comment]
We use the readMM function to bring in sparse matrices into the R environment. CellRanger creates the sparse matrices - we are just reading it in.

**Comment by vasighi** [comment]
Thank you very much
